<?php

/**
 * @file
 * Install, update and uninstall functions for the Mailer Plus module.
 */

declare(strict_types=1);

use Drupal\mailer_policy\Entity\MailerPolicy;

/**
 * Implements hook_requirements().
 */
function symfony_mailer_requirements($phase): array {
  $requirements = [];

  $packages = [
    'html2text/html2text' => 'Html2Text\Html2Text',
    'symfony/mailer' => 'Symfony\Component\Mailer\Mailer',
    'tijsverkoyen/css-to-inline-styles' => 'TijsVerkoyen\CssToInlineStyles\CssToInlineStyles',
  ];

  foreach ($packages as $name => $class) {
    if (!class_exists($class)) {
      $missing[] = $name;
    }
  }

  if (!empty($missing)) {
    $requirements['symfony_mailer_packages'] = [
      'title' => t('Symfony Mailer dependencies'),
      'value' => t('Required packages missing.'),
      'description' => implode(', ', $missing),
      'severity' => REQUIREMENT_ERROR,
    ];
  }

  return $requirements;
}

/**
 * Enable new dependency mailer_policy.
 */
function symfony_mailer_update_20001() {
  $module_installer = \Drupal::service('module_installer');
  $module_handler = \Drupal::service('module_handler');

  if (!$module_handler->moduleExists('mailer_policy')) {
    $module_installer->install(['mailer_policy']);
    // Delete default policy.
    foreach (MailerPolicy::loadMultiple() as $policy) {
      $policy->delete();
    }
  }
}

/**
 * Split configuration into the correct sub-modules.
 */
function symfony_mailer_update_20002() {
  $config_factory = \Drupal::configFactory();
  $module_installer = \Drupal::service('module_installer');
  $module_handler = \Drupal::service('module_handler');

  $map = [
    'symfony_mailer.mailer_policy' => 'mailer_policy.mailer_policy',
    'symfony_mailer.mailer_transport' => 'mailer_transport.mailer_transport',
  ];

  foreach ($map as $old_prefix => $new_prefix) {
    foreach ($config_factory->listAll($old_prefix) as $old_name) {
      $new_name = $new_prefix . substr($old_name, strlen($old_prefix));
      $config_factory->rename($old_name, $new_name);
    }
  }

  if ($settings = $config_factory->getEditable('symfony_mailer.settings')) {
    $config_factory->getEditable('mailer_transport.settings')->set('default_transport', $settings->get('default_transport'))->save();
    $override = $settings->get('override') ?? [];

    // Check we can combine the 2 contact overrides.
    if (isset($override['contact_form']) && (($override['contact_form'] == 3) xor ($override['contact'] == 3))) {
      throw new \Exception("Override setting for contact and contact_form must be equal in 2.x");
    }

    // Rename overrides.
    $rename = [
      'simplenews' => 'simplenews__subscriber',
      'simplenews_newsletter' => 'simplenews__newsletter',
      'contact_form' => 'contact',
      'commerce_order_type' => 'commerce_order',
    ];
    foreach ($rename as $old => $new) {
      if (isset($override[$old])) {
        $override[$new] = $override[$old];
        unset($override[$old]);
      }
    }

    if (!$module_handler->moduleExists('mailer_override')) {
      $module_installer->install(['mailer_override']);
    }

    $config_factory->getEditable('mailer_override.settings')->set('override', $override)->save();
    $settings->delete();
  }
}

/**
 * Adjustments to policy IDs.
 */
function symfony_mailer_update_20003() {
  $map = [
    '#(^[\w_]+\.[\w_]+)(\.[\w_]+)$#' => '$1.$2',
    '#^contact($|\.copy|\.mail)#' => 'contact.user$1',
    '#^contact_form#' => 'contact.page',
    '#^simplenews($|\.subscribe|\.validate)#' => 'simplenews.subscriber$1',
    '#^simplenews_newsletter#' => 'simplenews.newsletter',
    '#^commerce_order_type#' => 'commerce_order',
    '#^symfony_mailer.test#' => 'symfony_mailer.verify',
  ];

  foreach (MailerPolicy::loadMultiple() as $id => $policy) {
    foreach ($map as $pattern => $replacement) {
      $id = preg_replace($pattern, $replacement, $id);
    }

    if ($id != $policy->id()) {
      MailerPolicy::create(['id' => $id, 'configuration' => $policy->getConfiguration()])->save();
      $policy->delete();
    }
  }
}

/**
 * Adjustments to variable names.
 */
function symfony_mailer_update_20004() {
  $map = [
    'commerce_order' => 'commerce_order',
    'contact' => 'contact_message',
    'simplenews' => 'issue',
  ];

  foreach (MailerPolicy::loadMultiple() as $policy) {
    [$initial] = explode('.', $policy->getTag());
    if ($replacement = $map[$initial] ?? NULL) {
      $config = $policy->getConfiguration();
      if (isset($config['email_body']['content']['value'])) {
        $config['email_body']['content']['value'] = str_replace('{{ body }}', "{{ $replacement }}", $config['email_body']['content']['value'], $count);
        if ($count) {
          $policy->setConfiguration($config)->save();
        }
      }
    }
  }
}

/**
 * Combine "All" policy with single option.
 */
function symfony_mailer_update_20005() {
  $map = [
    'simplenews.newsletter' => 'simplenews.newsletter.node',
  ];

  foreach ($map as $old_id => $new_id) {
    if ($old = MailerPolicy::load($old_id)) {
      $new = MailerPolicy::loadOrCreate($new_id);
      $new->setConfiguration($new->getConfiguration() + $old->getConfiguration())->save();
      $old->delete();
    }
  }
}
